#!/usr/bin/env python3
import argparse
import sqlite3

try:
    import psycopg
except Exception:
    psycopg = None


CREATE_SQL = """
CREATE TABLE IF NOT EXISTS public.rounds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company" TEXT,
  "Sector 1" TEXT,
  "Tag" TEXT,
  "Female founder" TEXT,
  "Spin-off?" TEXT,
  "HQ" TEXT,
  "Round size (€M)" TEXT,
  "Date" TEXT,
  "Q" TEXT,
  "Lead" TEXT,
  "Co-lead / follow 1" TEXT,
  "follow 2" TEXT,
  "follow 3" TEXT,
  "follow 4" TEXT,
  "Debt" TEXT,
  "FX" TEXT
);
"""


def main():
    parser = argparse.ArgumentParser(description="Migrate rounds from SQLite to Postgres (Supabase).")
    parser.add_argument("--sqlite", required=True, help="Path to local SQLite rounds.db")
    parser.add_argument("--database-url", required=True, help="Postgres connection URL")
    parser.add_argument("--create-table", action="store_true", help="Create table if missing")
    parser.add_argument("--truncate", action="store_true", help="Truncate target table before import")
    args = parser.parse_args()

    if psycopg is None:
        raise RuntimeError("psycopg is required. Install dependencies from requirements.txt")

    sconn = sqlite3.connect(args.sqlite)
    scur = sconn.cursor()
    scur.execute("PRAGMA table_info(rounds)")
    cols = [r[1] for r in scur.fetchall() if r[1]]
    if not cols:
        raise RuntimeError("SQLite table rounds not found")

    col_sql = ", ".join([f'"{c}"' for c in cols])
    scur.execute(f"SELECT {col_sql} FROM rounds ORDER BY id")
    rows = scur.fetchall()
    sconn.close()

    pconn = psycopg.connect(args.database_url)
    pcur = pconn.cursor()
    try:
        if args.create_table:
            pcur.execute(CREATE_SQL)
        if args.truncate:
            pcur.execute("TRUNCATE TABLE public.rounds RESTART IDENTITY")

        placeholders = ", ".join(["%s"] * len(cols))
        insert_sql = f'INSERT INTO public.rounds ({col_sql}) VALUES ({placeholders})'
        pcur.executemany(insert_sql, rows)
        pcur.execute("SELECT setval(pg_get_serial_sequence('public.rounds', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.rounds), true)")
        pconn.commit()
    finally:
        pcur.close()
        pconn.close()

    print(f"Migrated {len(rows)} rows to Postgres")


if __name__ == "__main__":
    main()
